# #2.2 Methods part Two

이전 #2.1에서 `Deposit()`을 실행한 뒤에도 변경사항이 적용되지 않았던 이유는 Go언어에서 `object` 와 `struct` 에 관여하는 부분 때문이다.<br/>
`function` 이나 `method` 나 뭐가되었든 뭔가를 보내는 순간에 복사본이 만들어졌기 때문이다.<br/>
때문에 `Deposit()` 을 실행할 때, 해당 `account` 의 원본이 사용되는 것이 아닌 복사본이 만들어지고 적용되는 것이다.<br/>
이는 속해있는 `object` 들이 변경되기 원치 않을 때, 유용하게 사용될 수 있다.<br/>
하지만 지금 우리가 원하는 것은 복사본이 아닌 변경된 결과가 적용되어있는 원본이다.<br/>
이를 해결하기 위해서는 아래와 같이 `method` 을 변경한다.<br/>

`accounts/accounts.go`
``` go
// Deposit x amount on your account
func (a *Account) Deposit(amount int) { // Account 앞의 *이 핵심이다.
    a.balance += amount
}
```

`method` 의 매개변수 내 `struct` 앞에 *이 붙은 것을 볼 수 있다.<br/>
이는 `method` `Deposit()` 을 실행할 때, `object` 를 복사하지 않고 `Deposit()` 을 호출한 대상 `account` 를 사용하라는 뜻이다.<br/>
이것을 `pointer receiver` 라고 한다.<br/>

이제 출금하는 `method` 를 만들어보자.<br/>

`accounts/accounts.go`
``` go
// Withdraw x amount from tour account
func (a *Account) Withdraw(amount int) {
    a.balance -= amount
}
```

그리고 다시 `main.go` 를 수정하여 출금한 결과도 보여주자.<br/>
``` go
func main() {
    account := accounts.NewAccount("ningpop")
    account.Deposit(10)
    fmt.Println(account.Balance())
    account.Withdraw(20)
    fmt.Println(account.Balance())
}
```
실행 결과
```
10
-10
```

하지만 계좌에 잔액이 없다면 이렇게 음수로 나오게 해서는 안된다.<br/>
그렇다면 이제는 `Error Handling` 에 대해서 배워보자.<br/>
Go언어에는 `try - except` 나 `try - catch` 같은 문법이 없다.<br/>
우리 스스로 `error`를 `return`해주고 `error`를 직접 체크해주어야 한다.<br/>
불편할 수도 있지만 그만한 가치가 있다.<br/>
방금 작성한 `Withdraw()` 를 수정하여 `account` 의 `balance` 가 없다면 `error`를 발생할 수 있도록 수정해보자.<br/>

`accounts/accounts.go`
``` go
// Withdraw x amount from tour account
func (a *Account) Withdraw(amount int) error {
    if a.balance < amount {
        return errors.New("Can't withdraw you are poor")
    }
    a.balance -= amount
    return nil
}
```
코드에 주석을 남겨놓은 부분과 같이 Go언어에서의 `error` 사용은 두가지 방식이 있다.<br/>
또한, `Python` 과 `Javascript` 처럼 `None` 이나 `null`은 Go언어에서는 존재하지 않는다.<br/>
그 대신 `nil` 이라는 키워드를 사용한다.<br/>
`Withdraw()` 에서 받아오는 반환값을 활용하기 위해 `main.go` 를 수정해보자.<br/>

`main.go`
``` go
func main() {
    account := accounts.NewAccount("ningpop")
    account.Deposit(10)
    fmt.Println(account.Balance())
    err := account.Withdraw(20)
    if err != nil {
        log.Fatalln(err)
    }
    fmt.Println(account.Balance())
```

여기서 `log.Fatalln()`은 `err`를 출력하고 프로그램을 종료시키는 역할이다.<br/>

이제 이들을 실행해보면 아래와 같다.<br/>
실행 결과
```
10
2020/11/03 22:00:00 Can't withdraw you are poor
exit status 1
```

이제 `error`가 뜨는 것을 볼 수 있다.<br/>
이것이 Go언어에서 `Error Handling` 을 할 수 있는 방법이다.<br/>
Go언어에서 직접 `error` 를 처리해야되는 방식은 다른 언어와 달라서 프로그래머마다 호불호가 갈릴 수 있다.<br/>

이를 조금 더 편하게 하기 위해 Go언어에서는 `error` 를 위한 `variable` 를 만들 수 있다.<br/>
`error` 가 많다면 아래와 같이 만들어준다.<br/>
``` go
var errNoMoney = errors.New("Can't withdraw")
...
    if a.balance < amount {
        return errNoMoney
    }
```
이렇게 만드려면 `error` 를 위한 변수는 `err` 라는 접두사를 가져야 한다.<br/>